#!/usr/bin/env ruby
Bundler.require

class MyResponder < AvroMachine::Responder
  def self.protocol
    Avro::Protocol.parse(File.read(File.expand_path("../example.avpr", __FILE__)))
  end

  def message1(params)
    [1, 2, 3]
  end

  def hello_world(params)
    "Hello, #{params['name']}"
  end
end

class MyConnection < AvroMachine::Connection
  def self.responder
    MyResponder
  end
end

port = ENV.fetch('PORT', 9090).to_i
EventMachine.run do
  EventMachine.start_server('0.0.0.0', port, MyConnection)
end